[package]
name = "botw-map"
version = "0.1.0"
description = "BOTW Map"
authors = ["swap"]
edition = "2021"

[lib]
name = "botw_map_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32", features = ["bundled"] }

[profile.release]
codegen-units = 16
lto = "thin"
opt-level = 3
strip = true
